---
    # This playbook deploys kibana to the target machine.---
- include: "{{ role_path }}/tasks/setup-redhat.yml"
  when: ansible_os_family == 'RedHat'

- name: Install Kibana.
  package:
    name: "{{ kibana_package }}"
    state: "{{ kibana_package_state }}"
  become: yes

- name: Ensure Kibana is started and enabled at boot.
  service:
    name: kibana
    state: "{{ kibana_service_state }}"
    enabled: "{{ kibana_service_enabled }}"
  become: yes

- name: Copy Kibana configuration.
  template:
    src: "{{ kibana_config_template }}"
    dest: "{{ kibana_config_file_path }}"
    owner: root
    group: root
    mode: 0644
  notify: restart kibana
  become: yes

- name: "Open port {{ kibana_server_port }} through the firewall"
  firewalld:
    port: "{{ kibana_server_port }}/tcp"
    permanent: yes
    state: enabled

- name: Reload firewalld service
  systemd:
    name: firewalld
    state: reloaded