---

- name: Install Rsyslog
  package:
    name: rsyslog
    state: present

- name: Copy config file
  template:
    src: rsyslog.config.j2
    dest: /etc/rsyslog.config
    owner: root 
    group: root 
    mode: 0644

- name: Restart Rsyslog service
  service:
    name: rsyslog
    state: restarted