---
# defaults file for ansible-role-fluentd
fluentd_user: td-agent
fluentd_group: td-agent
fluentd_extra_groups: []
fluentd_package_name: td-agent
fluentd_config_dir: "/etc/td-agent"
fluentd_config_file: "{{ fluentd_config_dir }}/td-agent.conf"
fluentd_config_fragment_dir: "{{ fluentd_config_dir }}/conf.d"
fluentd_service_name: td-agent
fluentd_plugin_dir: "{{ fluentd_config_dir }}/plugin"
fluentd_flags: ""
fluentd_bin: "/usr/sbin/td-agent"
fluentd_gem_bin: "/usr/sbin/td-agent-gem"
fluentd_plugins_to_install: []
fluentd_plugins_to_create: []
fluentd_certs_dir: "{{ fluentd_config_dir }}/certs"
fluentd_configs: {}
fluentd_system_config: "log_level error"
fluentd_ca_key:
fluentd_ca_cert:
fluentd_ca_private_key_passphrase: ""
fluentd_buffer_path: /var/spool/fluentd
fluentd_unix_pipe_dir: /var/tmp/fluentd
fluentd_log_dir: "/var/log/{{ fluentd_service_name }}"
fluentd_log_file: "{{ fluentd_log_dir }}/{{ fluentd_service_name }}.log"
fluentd_pid_dir: /var/run/td-agent
fluentd_pid_file: "{{ fluentd_pid_dir }}/td-agent.pid"
