---

- name: Create fluentd group
  group:
    name: "{{ fluentd_group }}"
    state: present

- name: Create fluentd user
  user:
    name: "{{ fluentd_user }}"
    group: "{{ fluentd_group }}"

- name: Install required libs
  apt:
    name: "{{ item }}"
    update_cache: yes
  with_items: "{{ fluentd_required_libs }}"
  become: yes
  become_method: "sudo"

- name: Install fluentd gem
  gem:
    name: fluentd
    state: present
    version: "{{ fluentd_version }}"
    user_install: no
  notify: restart fluentd
  become: yes
  become_method: "sudo"

- name: Install fluentd plugin gems
  gem:
    name: "{{ item }}"
    state: present
    user_install: no
  with_items:
    - "{{ fluentd_plugins }}"
  notify: restart fluentd
  become: yes
  become_method: "sudo"